---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cat-postgres-pv-volume
  labels:
    type: local
    app: cat-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cat-postgres-pv-claim
  labels:
    app: cat-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cat-postgres
  template:
    metadata:
      labels:
        app: cat-postgres
    spec:
      containers:
        - image: "postgres:latest"
          imagePullPolicy: IfNotPresent
          name: cat-postgres
          env:
            - name: POSTGRES_USER
              value: bk
            - name: PGUSER
              value: bk
            - name: POSTGRES_PASSWORD
              value: bk
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: cat-postgres
  labels:
    app: cat-postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  #      nodePort: 31070
  selector:
    app: cat-postgres