apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/
namespace: prod
namePrefix: prod-
images:
  - name: gcr.io/pgtm-jlong/cat-service # used for Kustomize matching
    newTag: latest
patchesStrategicMerge:
  - patch-env.yaml
#  - patch-memorylimit.yaml
commonLabels:
  env: prod
replicas:
  - name: cat-service
    count: 1
