apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

namePrefix: prod-

patchesStrategicMerge:
  - patch-env.yaml
commonLabels:
  env: prod
replicas:
  - name: cat-service
    count: 1
