apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-service
spec:
  template:
    spec:
      containers:
        - name: cat-service
          resources:
            limits:
              memory: 256Mi
            requests:
              memory: 256Mi
