apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: gcr.io/pgtm-jlong/cat-service
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/gitcred
  name: dev-cat-service
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/overlays/dev
    repoURL: https://github.com/booternetes-III-springonetour-july-2021/cat-service-release-ops.git
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
