apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-cat-service
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/overlays/prod
    repoURL: https://github.com/booternetes-III-springonetour-july-2021/cat-service-release-ops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
