apiVersion: kpack.io/v1alpha1
kind: ClusterStack
metadata:
  name: booternetes-stack
spec:
  id: "io.buildpacks.stacks.bionic"
  buildImage:
    image: "paketobuildpacks/build:base-cnb"
  runImage:
    image: "paketobuildpacks/run:base-cnb"
---
apiVersion: kpack.io/v1alpha1
kind: ClusterStore
metadata:
  name: booternetes-store
spec:
  sources:
    - image: paketobuildpacks/builder:base
---
apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: booternetes-builder
  namespace: kpack
spec:
  tag: gcr.io/pgtm-jlong/booternetes-builder
  serviceAccount: kpack-bot
  stack:
    name: booternetes-stack
    kind: ClusterStack
  store:
    name: booternetes-store
    kind: ClusterStore
  order:
    - group:
        - id: paketo-buildpacks/java
    - group:
        - id: paketo-buildpacks/nodejs
