apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/configmap.yaml
  - ../../base/deployment.yaml
  - ../../base/service.yaml
namespace: dev
images:
  - name: gcr.io/pgtm-jlong/cat-service # used for Kustomize matching
    newTag: 0.0.1-SNAPSHOT
namePrefix: dev-
