apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
data:
  # Custom policy that defines role:image-updater and assigns
  # the image-updater user to the role.
  # There are two policy formats:
  # 1. Applications (which belong to a project):
  # p, <user/group>, <resource>, <action>, <project>/<object>
  # 2. All other resources:
  # p, <user/group>, <resource>, <action>, <object>
  policy.csv: |
    p, role:image-updater, applications, get, */*, allow
    p, role:image-updater, applications, update, */*, allow
    g, image-updater, role:image-updater

  # policy.default is the name of the default role which Argo CD will falls back to, when
  # authorizing API requests (optional). If omitted or empty, users may be still be able to login,
  # but will see no apps, projects, etc...
  policy.default: role:readonly
